# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            HydroCode Design
tagline:          ''
description:      "I'm Daniel, a **Canadian** software engineer.<br /><br />I'm also working on a <a href='http://titananalytics.com'>Titan Analytics.</a>"
url:              http://hydrocodedesign.com

author:
  name:           'Daniel Fagnan'
  url:            https://twitter.com/thehydroimpulse

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/thehydroimpulse
